#!/usr/bin/python3
# This code write by (Ms.nope)
# version 1
'''
import
'''
from colorama import Fore,init
import os
import time
init()
class color:
      green = '\033[92m'
      red = '\033[91m'
      End = '\033[0m'
      blue = '\033[34m'
      org = '\033[33m'
opt = "\nBig-Tool/> "
def cls():
    os.system("clear")
def ext():
    cls()
    print(color.green + "Exiting..." + color.End)
    exit(1)
def main1():
   try1 = str(input("\nInstalling completed - press Enter to continue..."))
   if(str(try1) == ''):
     usage2()
   else:
       usage2()
def main2():
    try2 = str(input("\npackage Update completed - press Enter to continue..."))
    if(str(try2) == ''):
      usage()
    else:
         usage()
def main3():
    try3 = str(input("\npackage Uninstalled - press Enter to contine..."))
    if(str(try3) == ''):
      usage()
    else:
        usage()
def usage():
    os.system("printf '\033]2;Big-Tool\a'")
    cls()
    print(color.green + """
       /$$$$$$$  /$$                /$$$$$$$$                  /$$
      | $$__  $$|__/               |__  $$__/                 | $$
      | $$  \ $$ /$$  /$$$$$$         | $$  /$$$$$$   /$$$$$$ | $$
      | $$$$$$$ | $$ /$$__  $$ /$$$$$$| $$ /$$__  $$ /$$__  $$| $$ """ + color.org + "version: 1.2.0" + color.green + """ 
      | $$__  $$| $$| $$  \ $$|______/| $$| $$  \ $$| $$  \ $$| $$
      | $$  \ $$| $$| $$  | $$        | $$| $$  | $$| $$  | $$| $$
      | $$$$$$$/| $$|  $$$$$$$        | $$|  $$$$$$/|  $$$$$$/| $$
      |_______/ |__/ \____  $$        |__/ \______/  \______/ |__/
                     /$$  \ $$                                    
                    |  $$$$$$/                                    
                     \______/ 
                     """ + color.blue + """
        ---------[ Ms.nope Github: """ + color.red + "https://github.com/msprogrammer2938 " + color.blue + "]--------" + color.End)
    print("\n{1}.Installing package")
    print("{2}.Update package")
    print("{3}.Uninstall package")
    print("{4}.Exit")
    choose = input(opt)
    if choose == '1':
      usage2()
    elif choose == '2':
        usage3()
    elif choose == '3':
        usage4()
    elif choose == '4':
        ext()
    elif choose == '':
        usage()
    elif choose == ' ':
        usage()
    elif choose == '  ':
        usage()
    else:
        cls()
        print(choose + color.red + " Not Found!" + color.End)
        try2 = str(input("press Enter..."))
        if(str(try2) == ''):
          usage()
        else:
            usage()
def usage2():
    os.system("printf '\033]2;Big-Tool/Installing packages\a'")
    cls()
    print("1.nmap")
    print("2.Aircrack-ng")
    print("3.Metasploit")
    print("4.wifite")
    print("5.sqlmap")
    print("6.social Enginners setoolkit")
    print("7.sqlninja")
    print("8.nikto")
    print("9.htop")
    print("10.neofetch & screenfetch")
    print("11.git")
    print("12.cewl")
    print("13.mein menu")
    choose2 = input(opt)
    if choose2 == '1':
      cls()
      os.system("sudo apt install nmap")
      mein1()
    elif choose2 == '2':
        cls()
        os.system("sudo apt install aircrack-ng")
        main1()
    elif choose2 == '3':
        cls()
        os.system("sudo apt install metasploit")
        main1()
    elif choose2 == '4':
        cls()
        os.system("sudo apt install wifite")
        main1()
    elif choose2 == '5':
        cls()
        os.system("sudo apt install sqlmap")
        main1()
    elif choose2 == '6':
        cls()
        os.system("sudo apt install setoolkit")
        main1()
    elif choose2 == '7':
        cls()
        os.system("sudo apt install sqlninja")
        main1()
    elif choose2 == '8':
        cls()
        os.system("sudo apt install nikto")
        main1()
    elif choose2 == '9':
        cls()
        os.system("sudo apt install htop")
        main1()
    elif choose2 == '10':
        cls()
        os.system("sudo apt install neofetch")
        os.system("sudo apt install screenfetch")
        main1()
    elif choose2 == '11':
        cls()
        os.system("sudo apt install git")
        main1()
    elif choose2 == '12':
        cls()
        os.system("sudo apt install cewl")
        main1()
    elif choose2 == '13':
        usage()
    elif choose2 == '':
        usage2()
    elif choose2 == ' ':
        usage2()
    elif choose2 == '\r':
        usage2()
    elif choose2 == '\n':
        usage2()
    else:
        usage2()
def usage3():
    os.system("printf '\033]2;Big-Tool/Update package\a'")
    cls()
    os.system("figlet Big-Tool")
    choose3 = str(input("\nEnter your package name: "))
    os.system("sudo apt remove " + choose3 + " && sudo apt install " + choose3)
    main2()
def usage4():
   ("printf '\033]2;Big-Tool/Uninstall package\a'")
   cls()
   os.system("figlet Big-Tool")
   choose4 = str(input("\nEnter your package name: "))
   os.system("sudo apt-get remove " + choose4)
   main3()
if __name__ == "__main__":
    try:
       usage()
    except KeyboardInterrupt:
        print("\nctrl + c")
        print(color.green + "\nExiting..." + color.End)
        exit(1)
