#!/usr/bin/python3
# This code write by (Mr.nope)
# version 1.3.0
'''
Import
'''
import os
try:
    from colorama import Fore,init
except ImportError:
    os.system("pip3 install colorama")
import time
import sys
# --------------------------------------------------------------------------------------------------------------
init()
big_Tool_Version = "Big-Tool 1.3.0"
class color:
      green = '\033[92m'
      red = '\033[91m'
      End = '\033[0m'
      blue = '\033[34m'
      org = '\033[33m'
opt = "\nBig-Tool/> "
def cls():
    os.system("clear")
def ext():
    cls()
    print(color.green + "Exiting..." + color.End)
    exit(1)
def main1():
   try1 = str(input("\nInstalling completed - press Enter to continue..."))
   if(str(try1) == ''):
     usage2()
   else:
       usage2()
def main2():
    try2 = str(input("\npackage Update completed - press Enter to continue..."))
    if(str(try2) == ''):
      usage()
    else:
         usage()
def main3():
    try3 = str(input("\npackage Uninstalled - press Enter to contine..."))
    if(str(try3) == ''):
      usage()
    else:
        usage()
def usage():
    os.system("printf '\033]2;Big-Tool\a'")
    cls()
    print(color.green + """
       /$$$$$$$  /$$                /$$$$$$$$                  /$$
      | $$__  $$|__/               |__  $$__/                 | $$
      | $$  \ $$ /$$  /$$$$$$         | $$  /$$$$$$   /$$$$$$ | $$
      | $$$$$$$ | $$ /$$__  $$ /$$$$$$| $$ /$$__  $$ /$$__  $$| $$ """ + color.org + big_Tool_Version + color.green + """ 
      | $$__  $$| $$| $$  \ $$|______/| $$| $$  \ $$| $$  \ $$| $$
      | $$  \ $$| $$| $$  | $$        | $$| $$  | $$| $$  | $$| $$
      | $$$$$$$/| $$|  $$$$$$$        | $$|  $$$$$$/|  $$$$$$/| $$
      |_______/ |__/ \____  $$        |__/ \______/  \______/ |__/
                     /$$  \ $$                                    
                    |  $$$$$$/                                    
                     \______/ 
                     """ + color.blue + """
        ---------[ Mr.nope Github: """ + color.red + "https://github.com/mrprogrammer2938 " + color.blue + "]--------" + color.End)
    print("\n{1}.Installing package")
    print("{2}.Update package")
    print("{3}.Uninstall package")
    print("{99}.Exit")
    choose = input(opt)
    if choose == '1':
      usage2()
    elif choose == '2':
        usage3()
    elif choose == '3':
        usage4()
    elif choose == '99':
        ext()
    elif choose == '':
        usage()
    elif choose == ' ':
        usage()
    elif choose == '  ':
        usage()
    else:
        cls()
        print(choose + color.red + " Not Found!" + color.End)
        try2 = input("press Enter...")
        if try2 == '':
          usage()
        else:
            usage()
def usage2():
    os.system("printf '\033]2;Big-Tool/Installing packages\a'")
    cls()
    print("01.Black-Tool")
    print("02.Black-Scan")
    print("03.nmap")
    print("04.Aircrack-ng")
    print("05.Metasploit")
    print("06.wifite")
    print("07.sqlmap")
    print("08.social Enginners setoolkit")
    print("09.sqlninja")
    print("10.nikto")
    print("11.htop")
    print("12.neofetch & screenfetch")
    print("13.git")
    print("14.cewl")
    print("99.mein menu")
    choose2 = input(opt)
    if choose2 == '1' or choose2 == '01':
        cls()
        os.system("git clone https://github.com/mrprogrammer2938/Black-Tool")
        main1()
    elif choose2 == '2' or choose2 == '02':
        cls()
        os.system("git clone https://github.com/mrprogrammer2938/Black-Scan")
        main1()
    elif choose2 == '3' or choose2 == '03':
        cls()
        os.system("sudo apt install nmap")
        main1()
    elif choose2 == '4' or choose2 == '04':
        cls()
        os.system("sudo apt install aircrack-ng")
        main1()
    elif choose2 == '5' or choose2 == '05':
        cls()
        os.system("sudo apt install metasploit")
        main1()
    elif choose2 == '6' or choose2 == '06':
        cls()
        os.system("sudo apt install wifite")
        main1()
    elif choose2 == '7' or choose2 == '07':
        cls()
        os.system("sudo apt install sqlmap")
        main1()
    elif choose2 == '8' or choose2 == '08':
        cls()
        os.system("sudo apt install setoolkit")
        main1()
    elif choose2 == '9' or choose2 == '09':
        cls()
        os.system("sudo apt install sqlninja")
        main1()
    elif choose2 == '10':
        cls()
        os.system("sudo apt install nikto")
        main1()
    elif choose2 == '11':
        cls()
        os.system("sudo apt install htop")
        main1()
    elif choose2 == '12':
        cls()
        os.system("sudo apt install neofetch")
        os.system("sudo apt install screenfetch")
        main1()
    elif choose2 == '13':
        cls()
        os.system("sudo apt install git")
        main1()
    elif choose2 == '14':
        cls()
        os.system("sudo apt install cewl")
        main1()
    elif choose2 == '99':
        usage()
    elif choose2 == '':
        usage2()
    elif choose2 == ' ':
        usage2()
    elif choose2 == '\r':
        usage2()
    elif choose2 == '\n':
        usage2()
    else:
        usage2()
def usage3():
    os.system("printf '\033]2;Big-Tool/Update package\a'")
    cls()
    os.system("figlet Big-Tool")
    choose3 = str(input("\nEnter your package name: "))
    os.system("sudo apt remove " + choose3 + " && sudo apt install " + choose3)
    main2()
def usage4():
   ("printf '\033]2;Big-Tool/Uninstall package\a'")
   cls()
   os.system("figlet Big-Tool")
   choose4 = str(input("\nEnter your package name: "))
   os.system("sudo apt-get remove " + choose4)
   main3()
if __name__ == "__main__":
    try:
       try:
           usage()
       except EOFError:
           print("\nCtrl + D\n\nExiting...\n")
           sys.exit()
    except KeyboardInterrupt:
        print("\nctrl + c")
        print(color.green + "\nExiting..." + color.End)
        sys.exit()